package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import com.example.data.preferences.AppLanguage

data class AppStrings(
    val appName: String,
    val greetingMorning: String,
    val greetingAfternoon: String,
    val greetingEvening: String,
    val guestUser: String,
    val todayAchievement: String,
    val tasksCompletedOf: String,
    val motivationalGreat: String,
    val motivationalKeepGoing: String,
    val motivationalAlmostDone: String,
    val motivationalStartDay: String,
    val motivationalCompletedAll: String,
    val tabToday: String,
    val tabTomorrow: String,
    val tabThisWeek: String,
    val tabLater: String,
    val tabAll: String,
    val navHome: String,
    val navMyTasks: String,
    val navCalendar: String,
    val navReminders: String,
    val navSettings: String,
    val navProfile: String,
    val addTask: String,
    val editTask: String,
    val taskTitle: String,
    val taskTitleHint: String,
    val taskDescription: String,
    val taskDescriptionHint: String,
    val category: String,
    val selectCategory: String,
    val date: String,
    val selectDate: String,
    val time: String,
    val selectTime: String,
    val allDay: String,
    val reminder: String,
    val repeat: String,
    val cardColor: String,
    val defaultColor: String,
    val customColor: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val complete: String,
    val uncomplete: String,
    val taskDeleted: String,
    val undo: String,
    val noTasksToday: String,
    val noTasksDescription: String,
    val searchTasks: String,
    val filterByCategory: String,
    val filterByStatus: String,
    val allStatus: String,
    val pendingStatus: String,
    val completedStatus: String,
    val upcomingStatus: String,
    val calendarMonth: String,
    val calendarWeek: String,
    val calendarDay: String,
    val upcomingReminders: String,
    val noReminders: String,
    val inMinutes: String,
    val inHours: String,
    val tomorrowAt: String,
    val customization: String,
    val themeMode: String,
    val primaryColor: String,
    val themeColorsHeadline: String,
    val fontSize: String,
    val fontFamily: String,
    val fontPreviewText: String,
    val cardCorners: String,
    val cardLayout: String,
    val cardShadow: String,
    val cardBorder: String,
    val notificationSound: String,
    val soundVolume: String,
    val testSound: String,
    val iconTheme: String,
    val language: String,
    val chooseLanguage: String,
    val login: String,
    val register: String,
    val logout: String,
    val email: String,
    val password: String,
    val fullName: String,
    val phoneNumber: String,
    val address: String,
    val jobTitle: String,
    val changePassword: String,
    val currentPassword: String,
    val newPassword: String,
    val confirmPassword: String,
    val userProfile: String,
    val editProfile: String,
    val avatarStyle: String,
    val profileSaved: String,
    val passwordChanged: String,
    val dontHaveAccount: String,
    val alreadyHaveAccount: String,
    val continueAsGuest: String,
    val loginSubtitle: String,
    val registerSubtitle: String,
    val aboutApp: String,
    val version: String,
    val appDescriptionText: String,
    val createCustomCategory: String,
    val categoryName: String,
    val categoryColor: String,
    val categoryIcon: String,
    val manageCategories: String,
    val quickAdd: String,
    val minutesLeft: String,
    val hoursLeft: String,
    val daysLeft: String,
    val overdue: String,
    val priority: String,
    val priorityHigh: String,
    val priorityMedium: String,
    val priorityLow: String,
    val sortBy: String,
    val sortByDateTime: String,
    val sortByPriority: String,
    val sortByAlpha: String,
    val sortByDate: String,
    val sortByCategory: String,
    val sortByTitle: String,
    val locationReminder: String,
    val locationPlaceName: String,
    val locationHint: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,
    val confirmDeleteTitle: String,
    val confirmDeleteMessage: String,
    val moveToTrash: String,
    val trash: String,
    val emptyTrash: String,
    val restoreTask: String,
    val restore: String,
    val deletePermanently: String,
    val permanentlyDelete: String,
    val emptyTrashConfirm: String,
    val confirmEmptyTrashMessage: String,
    val trashEmpty: String,
    val notes: String,
    val openCardDetails: String,
    val independentSound: String,
    val independentSoundDesc: String,
    val shareApp: String,
    val pressBackAgainToExit: String
)

val ArabicStrings = AppStrings(
    appName = "إنجاز",
    greetingMorning = "صباح الخير،",
    greetingAfternoon = "مساء الخير،",
    greetingEvening = "أهلاً بك،",
    guestUser = "صديق إنجاز",
    todayAchievement = "إنجاز اليوم",
    tasksCompletedOf = "%d من %d مهام",
    motivationalGreat = "أداء رائع، استمر!",
    motivationalKeepGoing = "بداية موفقة، واصل التقدم!",
    motivationalAlmostDone = "أنت على وشك الانتهاء، رائع!",
    motivationalStartDay = "ابدأ يومك بإنجاز أول مهمة!",
    motivationalCompletedAll = "مبارك! أنجزت جميع مهام اليوم بنجاح 🎉",
    tabToday = "اليوم",
    tabTomorrow = "غداً",
    tabThisWeek = "هذا الأسبوع",
    tabLater = "لاحقاً",
    tabAll = "الكل",
    navHome = "الرئيسية",
    navMyTasks = "مهامي",
    navCalendar = "التقويم",
    navReminders = "التذكيرات",
    navSettings = "الإعدادات",
    navProfile = "الملف الشخصي",
    addTask = "إضافة مهمة جديدة",
    editTask = "تعديل المهمة",
    taskTitle = "عنوان المهمة",
    taskTitleHint = "ما الذي تريد إنجازه؟",
    taskDescription = "الملاحظات أو التفاصيل (اختياري)",
    taskDescriptionHint = "أضف أي تفاصيل وملاحظات إضافية هنا...",
    category = "التصنيف",
    selectCategory = "اختر التصنيف",
    date = "التاريخ",
    selectDate = "تحديد التاريخ",
    time = "الوقت",
    selectTime = "تحديد الوقت",
    allDay = "طوال اليوم",
    reminder = "التذكير والمنبه",
    repeat = "التكرار",
    cardColor = "لون البطاقة المخصص",
    defaultColor = "افتراضي",
    customColor = "مخصص",
    save = "حفظ المهمة",
    cancel = "إلغاء",
    delete = "حذف",
    complete = "إنجاز",
    uncomplete = "إلغاء الإنجاز",
    taskDeleted = "تم نقل المهمة إلى سلة المهملات",
    undo = "تراجع",
    noTasksToday = "لا توجد مهام مجدولة",
    noTasksDescription = "يومك هادئ ومريح! اضغط على + لإضافة أول مهمة لك اليوم.",
    searchTasks = "البحث في المهام والملاحظات...",
    filterByCategory = "حسب التصنيف",
    filterByStatus = "حسب الحالة",
    allStatus = "الكل",
    pendingStatus = "غير المكتملة",
    completedStatus = "المكتملة",
    upcomingStatus = "القادمة",
    calendarMonth = "شهري",
    calendarWeek = "أسبوعي",
    calendarDay = "يومي",
    upcomingReminders = "التذكيرات القادمة",
    noReminders = "لا توجد تذكيرات مجدولة حالياً",
    inMinutes = "بعد %d دقيقة",
    inHours = "بعد %d ساعة",
    tomorrowAt = "غداً — %s",
    customization = "التصميم والتنسيقات",
    themeMode = "المظهر والوضع",
    primaryColor = "اللون الرئيسي وسمة التطبيق",
    themeColorsHeadline = "ألوان وسمات التطبيق",
    fontSize = "حجم الخط",
    fontFamily = "نوع الخط المفضل",
    fontPreviewText = "معاينة نمط وشكل الخط المختار",
    cardCorners = "شكل البطاقات",
    cardLayout = "تنسيق عرض البطاقات",
    cardShadow = "تأثير التظليل والعمق",
    cardBorder = "تلوين وتنسيق الحواف",
    notificationSound = "نغمة التنبيه المنفصلة",
    soundVolume = "مستوى صوت التنبيه",
    testSound = "تجربة الصوت",
    iconTheme = "نمط وأناقة الأيقونات",
    language = "اللغة",
    chooseLanguage = "تغيير لغة التطبيق",
    login = "تسجيل الدخول",
    register = "إنشاء حساب جديد",
    logout = "تسجيل الخروج",
    email = "البريد الإلكتروني",
    password = "كلمة المرور",
    fullName = "الاسم الكامل",
    phoneNumber = "رقم الهاتف",
    address = "العنوان والمدينة",
    jobTitle = "المسمى الوظيفي / النبذة",
    changePassword = "تغيير كلمة المرور",
    currentPassword = "كلمة المرور الحالية",
    newPassword = "كلمة المرور الجديدة",
    confirmPassword = "تأكيد كلمة المرور",
    userProfile = "حساب المستخدم",
    editProfile = "تعديل البيانات الشخصية",
    avatarStyle = "الصورة الرمزية والشخصية",
    profileSaved = "تم حفظ التعديلات بنجاح",
    passwordChanged = "تم تغيير كلمة المرور بنجاح",
    dontHaveAccount = "ليس لديك حساب؟ أنشئ حساباً الآن",
    alreadyHaveAccount = "لديك حساب بالفعل؟ سجل دخولك",
    continueAsGuest = "المتابعة السريعة كضيف",
    loginSubtitle = "سجل دخولك لمتابعة مهامك اليومية وتنظيم يومك",
    registerSubtitle = "أنشئ حسابك لبدء تجربة إنجاز الفريدة",
    aboutApp = "حول التطبيق",
    version = "الإصدار 2.1 المحدث",
    appDescriptionText = "تطبيق إنجاز هو مدير مهام وتذكيرات يومية شخصي، فائق السرعة، خفيف، وذو واجهة حديثة مصممة لمساعدتك على تنظيم يومك وزيادة إنتاجيتك بكل سلاسة مع دعم الأولويات والملاحظات والتذكيرات.",
    createCustomCategory = "إنشاء تصنيف جديد",
    categoryName = "اسم التصنيف",
    categoryColor = "لون التصنيف",
    categoryIcon = "أيقونة التصنيف",
    manageCategories = "إدارة التصنيفات",
    quickAdd = "إضافة سريعة",
    minutesLeft = "متبقي %d دقيقة",
    hoursLeft = "متبقي %d ساعة",
    daysLeft = "متبقي %d يوم",
    overdue = "متأخرة",
    priority = "أولوية المهمة",
    priorityHigh = "عالية 🔴",
    priorityMedium = "متوسطة 🟡",
    priorityLow = "منخفضة 🟢",
    sortBy = "الترتيب",
    sortByDateTime = "حسب التاريخ والوقت",
    sortByPriority = "حسب الأولوية",
    sortByAlpha = "أبجدياً (أ-ي)",
    sortByDate = "حسب التاريخ",
    sortByCategory = "حسب التصنيف",
    sortByTitle = "حسب العنوان",
    locationReminder = "تذكير بالموقع الجغرافي",
    locationPlaceName = "اسم المكان أو الوجهة",
    locationHint = "مثلاً: المنزل، السوبرماركت، العمل، المشفى...",
    deleteConfirmTitle = "تنبيه عند الحذف",
    deleteConfirmMessage = "هل تريد نقل هذه المهمة إلى سلة المهملات؟ يمكنك استعادتها لاحقاً في أي وقت.",
    confirmDeleteTitle = "تنبيه عند الحذف",
    confirmDeleteMessage = "هل تريد نقل هذه المهمة إلى سلة المهملات؟ يمكنك استعادتها لاحقاً في أي وقت.",
    moveToTrash = "نقل إلى السلة",
    trash = "سلة المهملات",
    emptyTrash = "إفراغ سلة المهملات",
    restoreTask = "استعادة المهمة",
    restore = "استعادة",
    deletePermanently = "حذف نهائي",
    permanentlyDelete = "حذف نهائي",
    emptyTrashConfirm = "هل أنت متأكد من حذف جميع المهام في سلة المهملات نهائياً؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmEmptyTrashMessage = "هل أنت متأكد من حذف جميع المهام في سلة المهملات نهائياً؟ لا يمكن التراجع عن هذا الإجراء.",
    trashEmpty = "سلة المهملات فارغة تماماً",
    notes = "ملاحظات",
    openCardDetails = "فتح تفاصيل المهمة",
    independentSound = "تفعيل الصوت مستقل عن النظام",
    independentSoundDesc = "تشغيل نغمات التنبيه عبر مسار الصوت الخاص المباشر حتى عند كتم نغمات النظام العامة",
    shareApp = "مشاركة التطبيق",
    pressBackAgainToExit = "اضغط مرة أخرى للخروج من التطبيق"
)

val EnglishStrings = AppStrings(
    appName = "Enjaz",
    greetingMorning = "Good morning,",
    greetingAfternoon = "Good afternoon,",
    greetingEvening = "Good evening,",
    guestUser = "Enjaz Friend",
    todayAchievement = "Today's Achievement",
    tasksCompletedOf = "%d of %d tasks",
    motivationalGreat = "Great job, keep it up!",
    motivationalKeepGoing = "Good start, keep progressing!",
    motivationalAlmostDone = "Almost there, fantastic!",
    motivationalStartDay = "Start your day with your first task!",
    motivationalCompletedAll = "Awesome! You finished all today's tasks 🎉",
    tabToday = "Today",
    tabTomorrow = "Tomorrow",
    tabThisWeek = "This Week",
    tabLater = "Later",
    tabAll = "All",
    navHome = "Home",
    navMyTasks = "My Tasks",
    navCalendar = "Calendar",
    navReminders = "Reminders",
    navSettings = "Settings",
    navProfile = "Profile",
    addTask = "Add New Task",
    editTask = "Edit Task",
    taskTitle = "Task Title",
    taskTitleHint = "What would you like to accomplish?",
    taskDescription = "Notes or details (optional)",
    taskDescriptionHint = "Add any extra details or notes here...",
    category = "Category",
    selectCategory = "Select Category",
    date = "Date",
    selectDate = "Select Date",
    time = "Time",
    selectTime = "Select Time",
    allDay = "All Day",
    reminder = "Reminder & Alarm",
    repeat = "Repeat",
    cardColor = "Custom Card Color",
    defaultColor = "Default",
    customColor = "Custom",
    save = "Save Task",
    cancel = "Cancel",
    delete = "Delete",
    complete = "Complete",
    uncomplete = "Mark Incomplete",
    taskDeleted = "Task moved to trash",
    undo = "Undo",
    noTasksToday = "No tasks scheduled",
    noTasksDescription = "Your day is free! Tap + to create your first task today.",
    searchTasks = "Search tasks & notes...",
    filterByCategory = "By Category",
    filterByStatus = "By Status",
    allStatus = "All",
    pendingStatus = "Pending",
    completedStatus = "Completed",
    upcomingStatus = "Upcoming",
    calendarMonth = "Month",
    calendarWeek = "Week",
    calendarDay = "Day",
    upcomingReminders = "Upcoming Reminders",
    noReminders = "No reminders scheduled right now",
    inMinutes = "In %d minutes",
    inHours = "In %d hours",
    tomorrowAt = "Tomorrow — %s",
    customization = "Theme & Customization",
    themeMode = "Theme Mode",
    primaryColor = "Theme & Primary Color",
    themeColorsHeadline = "App Themes & Colors",
    fontSize = "Font Size",
    fontFamily = "Font Family Style",
    fontPreviewText = "Font Style & Typeface Preview",
    cardCorners = "Card Shape",
    cardLayout = "Card Layout Format",
    cardShadow = "Card Depth & Shadow",
    cardBorder = "Border Styling & Glow",
    notificationSound = "Custom Alert Tone",
    soundVolume = "Alert Volume",
    testSound = "Play Tone",
    iconTheme = "Icon Styling",
    language = "Language",
    chooseLanguage = "Change App Language",
    login = "Sign In",
    register = "Create Account",
    logout = "Sign Out",
    email = "Email Address",
    password = "Password",
    fullName = "Full Name",
    phoneNumber = "Phone Number",
    address = "Address & City",
    jobTitle = "Job Title / Bio",
    changePassword = "Change Password",
    currentPassword = "Current Password",
    newPassword = "New Password",
    confirmPassword = "Confirm Password",
    userProfile = "User Account",
    editProfile = "Edit Profile Info",
    avatarStyle = "Avatar & Profile Icon",
    profileSaved = "Profile updated successfully",
    passwordChanged = "Password changed successfully",
    dontHaveAccount = "Don't have an account? Sign up",
    alreadyHaveAccount = "Already have an account? Sign in",
    continueAsGuest = "Quick Continue as Guest",
    loginSubtitle = "Sign in to organize your day and boost productivity",
    registerSubtitle = "Create your account to experience Enjaz",
    aboutApp = "About App",
    version = "Version 2.1",
    appDescriptionText = "Enjaz is a lightweight, ultra-fast personal daily task and reminder manager designed with modern elegance to keep you focused and organized.",
    createCustomCategory = "Create Custom Category",
    categoryName = "Category Name",
    categoryColor = "Category Color",
    categoryIcon = "Category Icon",
    manageCategories = "Manage Categories",
    quickAdd = "Quick Add",
    minutesLeft = "%d min left",
    hoursLeft = "%d hours left",
    daysLeft = "%d days left",
    overdue = "Overdue",
    priority = "Task Priority",
    priorityHigh = "High 🔴",
    priorityMedium = "Medium 🟡",
    priorityLow = "Low 🟢",
    sortBy = "Sort By",
    sortByDateTime = "By Date & Time",
    sortByPriority = "By Priority",
    sortByAlpha = "Alphabetical (A-Z)",
    sortByDate = "By Date",
    sortByCategory = "By Category",
    sortByTitle = "By Title",
    locationReminder = "Location Reminder",
    locationPlaceName = "Place / Destination Name",
    locationHint = "e.g. Home, Supermarket, Work, Hospital...",
    deleteConfirmTitle = "Confirm Deletion",
    deleteConfirmMessage = "Move this task to trash? You can restore it anytime from trash.",
    confirmDeleteTitle = "Confirm Deletion",
    confirmDeleteMessage = "Move this task to trash? You can restore it anytime from trash.",
    moveToTrash = "Move to Trash",
    trash = "Trash / Recycle Bin",
    emptyTrash = "Empty Trash",
    restoreTask = "Restore Task",
    restore = "Restore",
    deletePermanently = "Delete Permanently",
    permanentlyDelete = "Delete Permanently",
    emptyTrashConfirm = "Are you sure you want to permanently delete all tasks in the trash? This cannot be undone.",
    confirmEmptyTrashMessage = "Are you sure you want to permanently delete all tasks in the trash? This cannot be undone.",
    trashEmpty = "Trash is completely empty",
    notes = "Notes",
    openCardDetails = "Open Task Details",
    independentSound = "Independent Audio Stream",
    independentSoundDesc = "Play notification tone directly via synthesis audio stream independent of system ringer profile",
    shareApp = "Share App",
    pressBackAgainToExit = "Press back again to exit"
)

val LocalAppStrings = staticCompositionLocalOf { ArabicStrings }

object AppStringsProvider {
    val current: AppStrings
        @Composable
        @ReadOnlyComposable
        get() = LocalAppStrings.current

    fun getStrings(language: AppLanguage): AppStrings {
        return if (language == AppLanguage.EN) EnglishStrings else ArabicStrings
    }
}
